### ISSUE TITLE
Only drug and duration extracted

### ISSUE THREAD

**Issue by HarsheetKakar** [NLPatVCU/medaCy#183]
#### Description
The example provided showed that Drug, Dosage, Form, and Duration are extracted from the given clinical text. After installing the library (Developer branch) only Drug and Duration was extracted from the given text.

#### Steps/Code to Reproduce
```
>>> pip install git+https://github.com/NLPatVCU/medaCy.git@development
>>> pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git

from medacy.model.model import Model

model = Model.load_external('medacy_model_clinical_notes')
annotation = model.predict("The patient was prescribed 1 capsule of Advil for 5 days.")
print(annotation)
```

#### Expected Results
```
[
    ('Drug', 40, 45, 'Advil'),
    ('Dosage', 27, 28, '1'), 
    ('Form', 29, 36, 'capsule'),
    ('Duration', 46, 56, 'for 5 days')
]
```

#### Actual Results
```
[('Drug', 40, 45, 'Advil'), ('Duration', 46, 56, 'for 5 days')]
```

**Comment by HarsheetKakar** [comment]
>>> import sys; print("Python", sys.version)
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.18.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.4.1
>>> import medacy; print("medacy", medacy.__version__)
medacy 1.0.0

**Comment by prabhatM** [comment]
I got the similar result.

**Comment by sherwin7** [comment]
@HarsheetKakar  ya i got what's your problem is, since medacy is a spacy based model it scans from left to right of the sentence if it gets the name of the drugs from there it will extract all the information even by mistake you leave a extra space between the words it wont able to extract the information

i have modified you sentence a little bit except dosage everything came 
here is the code

from medacy.model.model import Model

model = Model.load_external('medacy_model_clinical_notes')
annotation = model.predict("The patient was prescribed Advil 1 capsule for 5 days.")
print(annotation)


and the result is 
('Drug', 27, 32, 'Advil')
('Strength', 33, 34, '1')
('Form', 35, 42, 'capsule')
('Duration', 43, 53, 'for 5 days')

**Comment by prabhatM** [comment]
Thank you.
