### ISSUE TITLE
Can i able to train the model with custom dataset [FEATURE REQUEST]

### ISSUE THREAD

**Issue by sherwin7** [NLPatVCU/medaCy#194]
**What problem does your feature solve?**
can i able to train the model for my custom dataset like transer-learning

is there any chance a future update will come like that?

**Comment by swfarnsworth** [comment]
Once you have a dataset in the BRAT format, you can create a model using our command-line interface. Please let me know if anything about our documentation in that regard is unclear so that I can improve it accordingly.

BRAT format: https://brat.nlplab.org/standoff.html (medaCy only uses entity annotations, which are marked with a T)
CLI documentation: https://github.com/NLPatVCU/medaCy/blob/master/guide/command_line_interface.md
