### ISSUE TITLE
Consider supporting Python 3.6 until official support ends [FEATURE REQUEST]

### ISSUE THREAD

**Issue by DeniVuMedi** [NLPatVCU/medaCy#197]
**What problem does your feature solve?**
The current codebase I'm working on uses python `3.6.9`. We're not that far from upgrading to `3.7` but due to the project size, the upgrade itself wouldn't be trivial.

**Describe the solution you'd like**
Consider supporting Python `3.6` until official support ends (`2021-12-23`)

**Describe alternatives you've considered**
As mentioned we're not far from version `3.7` but upgrading wouldn't be trivial. If your codebase doesn't use `3.7.` specific features you might consider supporting `3.6.` for roughly a year more?

**Additional context**
Ubuntu `18.04 LTS` uses python `3.6.9` by default so supporting `3.6.` may cover a wide range of developers who are still using the default version provided by the OS.

Thanks in advance

**Comment by swfarnsworth** [comment]
I realize this has likely been frustrating for you and I apologize for that. As I recall, dataclasses are the only component that require 3.7 and there is a backport to be able to use them in 3.6. If this is the case, I'm going to drop the minimum version to 3.6 and update the requirements so that the backport is installed when the python version is 3.6.

**Comment by DeniVuMedi** [comment]
Thank you for a quick response. Not to worry about frustration, I don't mean to cause any inconvenience as well.
I Will monitor the issue, thanks again for a quick response.
