### ISSUE TITLE
Not sure where I am going wrong here.

### ISSUE THREAD

**Issue by theCuriousHAT** [NLPatVCU/medaCy#206]
#### The conflict is caused by:
    The user requested medacy 1.0.0 (from git+https://github.com/NLPatVCU/medaCy.git@v1.0.0)
    medacy-model-clinical-notes 1.0.1 depends on medacy 1.0.0 (from https://github.com/NLPatVCU/medaCy/archive/v1.0.0.tar.gz)

#### Versions

>>> import platform; print(platform.platform())
Windows-10-10.0.19041-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.6.3

**Comment by swfarnsworth** [comment]
Hey there @theCuriousHAT, sorry to hear that you've run into trouble. Could you tell me what the error message is?

**Comment by swfarnsworth** [comment]
I apologize, I suppose the console output at "The conflict is caused by:" contains part of the error message.

My guess is that pip doesn't recognize that `git+https://github.com/NLPatVCU/medaCy.git@v1.0.0` and `https://github.com/NLPatVCU/medaCy/archive/v1.0.0.tar.gz` contain identical code. 

Try making a new virtual environment, updating pip, and running `pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git` *without* first installing medaCy separately. Let me know if that does or does not solve the problem and I'll update the `setup.py` file accordingly.
